defaults:
  - image_normalization@image.normalization.kwargs: imagenet

set_mapping:
  images: image
  texts: text

image:
  # Image is resized before being cropped to train_resolution.
  train_resize_size: 256
  train_resolution: 224
  test_resize_size: 256
  test_resolution: 224

  train_resize:
    name: Resize
    kwargs: 
      height: ${....image.train_resize_size} 
      width: ${....image.train_resize_size} 
  train_crop:
    name: RandomCrop
    kwargs:
      height: ${....image.train_resolution} 
      width: ${....image.train_resolution} 

  test_resize:
    name: Resize
    kwargs: 
      height: ${....image.test_resize_size} 
      width: ${....image.test_resize_size} 
  test_crop:
    name: CenterCrop
    kwargs:
      height: ${....image.test_resolution} 
      width: ${....image.test_resolution} 

  normalization:
    name: ImageNormalization
  to_tensor:
    name: ImageToTensor
    kwargs: {}

text:
  normalization:
    name: TextNormalization
    kwargs: {}
  tokenization:
    name: NltkTokenization
    kwargs: {}
  sentence_padding:
    name: StartEndPadding
    kwargs: {}
  vocabulary:
    name: VocabularyEncoding
    kwargs:
      path: ${paths.transforms_dir}/${data.dataset.name}_train_vocabulary.pkl
  to_tensor:
    name: IndicesToTensor
    kwargs: {}
