channels:
  - defaults
  - conda-forge
  - pytorch
dependencies:
  - cpuonly
  - python=3.7
  - pytorch=1.8
  - torchvision=0.9
  - pytorch-lightning=1.3
  - torchmetrics=0.3
  - nltk=3.5
  - matplotlib
  - pip
  - pip:
    - hydra-core --upgrade --pre
    - albumentations
