channels:
  - defaults
  - conda-forge
  - pytorch
dependencies:
  - cudatoolkit=10.2
  - python=3.7
  - pytorch=1.8
  - torchvision=0.9
  - pytorch-lightning=1.3
  - torchmetrics=0.3
  - nltk=3.5
  - matplotlib
  - pip
